spring:
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    minimumIdle: 5
    maximumPoolSize: 5
graphql:
  playground:
    settings:
      request:
        credentials: include
  servlet:
    exception-handlers-enabled: true
    corsEnabled: true
    cors:
      allowed-origins:
        - 'http://localhost:3000'
        - 'https://auctions-demo.netlify.app'
      allow-credentials: true
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
auctions:
  pagination:
    max-items: 150
    max-images: 50
    max-profile-items: 50
  session:
    durationInMinutes: 60
scheduler:
  fixed-rate:
    delete-expired-tokens: 1800000  # 30 minutes
    conclude-expired-auctions: 300000  # 5 minutes
caching:
  caffeine:
    -
      names: sessionToken
      ttl-in-seconds: 120
      max-size: 100
    -
      names: watchedItems, bidItems, items
      ttl-in-seconds: 86400  # 1 day
      max-size: 100
