spring:
  jpa:
    show-sql: true
  datasource:
    minimumIdle: 5
    maximumPoolSize: 5
graphql:
  servlet:
    corsEnabled: true
    cors:
      allowed-origins:
        - '*'
#      allow-credentials: true
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
auctions:
  pagination:
    max-items: 150
    max-images: 50