spring:
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    minimumIdle: 5
    maximumPoolSize: 5
  cache:
    cache-names: sessionToken
    caffeine:
      spec: expireAfterWrite=120s
graphql:
  playground:
    settings:
      request:
        credentials: include
  servlet:
    exception-handlers-enabled: true
    corsEnabled: true
    cors:
      allowed-origins:
        - '*'
#      allow-credentials: true
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
auctions:
  pagination:
    max-items: 150
    max-images: 50
    max-profile-items: 50
  session:
    durationInMinutes: 60