spring:
  jpa:
    show-sql: true
graphql:
  servlet:
    corsEnabled: true
    cors:
      allowed-origins:
        - '*'
#      allow-credentials: true
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
auctions:
  pagination:
    max-items: 150
    max-images: 50