name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      MIN_COVERAGE_PERCENTAGE: 95
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean test -Dcoverage.min=$MIN_COVERAGE_PERCENTAGE -P github

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with:
          files: ./target/jacoco/jacoco.xml
